"""add_task_name_description_to_agent_tasks

Revision ID: 1180be293ea9
Revises: f3a2b1c4d5e6
Create Date: 2026-09-02 01:28:34.025484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1180be293ea9'
down_revision: Union[str, Sequence[str], None] = 'f3a2b1c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_tasks', sa.Column('task_name', sa.String(), nullable=True))
    op.add_column('agent_tasks', sa.Column('task_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_tasks', 'task_description')
    op.drop_column('agent_tasks', 'task_name')
    # ### end Alembic commands ###
