"""add_auth_subscription_task_session_tables

Revision ID: 6599b1fdbbd6
Revises: e9ce85d5d731
Create Date: 2026-07-15 18:39:06.748862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6599b1fdbbd6'
down_revision: Union[str, Sequence[str], None] = 'e9ce85d5d731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_subscriptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agent_slug_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PRE_INIT', 'INITIALIZING', 'ACTIVE', 'PAUSED', 'EXPIRED', name='subscriptionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_slug_id'], ['agent_slugs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_app_auths',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ai_name', sa.String(), nullable=False),
    sa.Column('auth_type', sa.String(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ai_name', name='uq_ai_app_auths_user_ai_name')
    )
    op.create_table('third_party_auths',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_type', sa.String(), server_default='Bearer', nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('provider_user_id', sa.String(), nullable=True),
    sa.Column('provider_username', sa.String(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_third_party_auths_user_provider')
    )
    # agent_tasks is created WITHOUT the circular FK to ai_app_sessions.
    # That FK is added below via ALTER TABLE after ai_app_sessions exists.
    op.create_table('agent_tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('agent_subscription_id', sa.UUID(), nullable=False),
    sa.Column('task_slug', sa.String(), nullable=False),
    sa.Column('current_phase_id', sa.UUID(), nullable=True),
    sa.Column('current_active_session_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_subscription_id'], ['agent_subscriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_phase_id'], ['pipeline_phases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_app_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('ai_app_auth_id', sa.UUID(), nullable=True),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('chat_session_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', 'FAILED', name='sessionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ai_app_auth_id'], ['ai_app_auths.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Add the circular FK now that both tables exist.
    op.create_foreign_key(
        'fk_agent_tasks_current_active_session_id',
        'agent_tasks', 'ai_app_sessions',
        ['current_active_session_id'], ['id'],
        ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_agent_tasks_current_active_session_id', 'agent_tasks', type_='foreignkey')
    op.drop_table('ai_app_sessions')
    op.drop_table('agent_tasks')
    op.drop_table('third_party_auths')
    op.drop_table('ai_app_auths')
    op.drop_table('agent_subscriptions')
    sa.Enum(name='subscriptionstatus').drop(op.get_bind())
    sa.Enum(name='sessionstatus').drop(op.get_bind())
    # ### end Alembic commands ###
