"""connected userstable to auth users id

Revision ID: a43a7e72bce8
Revises: 
Create Date: 2026-06-19 00:59:43.487152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a43a7e72bce8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('user_type', sa.Enum('SINGLE_USER', 'ORG_MEMBER', 'ORG_ADMIN', name='usertype'), nullable=False),
    sa.Column('user_status', sa.Enum('ACTIVE', 'SUSPENDED', 'DELETED', 'ACCOUNT_NOT_CREATED', 'ACCOUNT_NOT_VERIFIED', name='userstatus'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_foreign_key(
        constraint_name="fk_users_auth_id",
        source_table="users",
        referent_table="users",  # The target table in Supabase
        local_cols=["id"],       # The column in public.users
        remote_cols=["id"],      # The column in auth.users
        referent_schema="auth",  # Tells Postgres to look outside the public schema
        ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_users_auth_id", table_name="users", type_="foreignkey")
    op.drop_table('users')
    # ### end Alembic commands ###
