"""rename_prompt_url_to_prompt_add_oauth_state

Revision ID: ac7c75b20ba7
Revises: 6599b1fdbbd6
Create Date: 2026-09-02 00:49:22.289821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac7c75b20ba7'
down_revision: Union[str, Sequence[str], None] = '6599b1fdbbd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_subscriptions', sa.Column('oauth_state', sa.String(), nullable=True))
    op.add_column('pipeline_phases', sa.Column('prompt', sa.Text(), nullable=False))
    op.drop_column('pipeline_phases', 'prompt_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_phases', sa.Column('prompt_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('pipeline_phases', 'prompt')
    op.drop_column('agent_subscriptions', 'oauth_state')
    # ### end Alembic commands ###
