"""Add agent slug, pipeline phases, and allowed ai tables

Revision ID: fa54b90e21f9
Revises: a43a7e72bce8
Create Date: 2026-07-07 23:08:46.543517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa54b90e21f9'
down_revision: Union[str, Sequence[str], None] = 'a43a7e72bce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_slugs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('slug_name', sa.String(), nullable=False),
    sa.Column('agent_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug_name')
    )
    op.create_table('allowed_ai_models',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('agent_slug_id', sa.UUID(), nullable=False),
    sa.Column('ai_name', sa.String(), nullable=False),
    sa.Column('custom_agent_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_slug_id'], ['agent_slugs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_phases',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('agent_slug_id', sa.UUID(), nullable=False),
    sa.Column('phase_name', sa.String(), nullable=False),
    sa.Column('phase_number', sa.Integer(), nullable=False),
    sa.Column('prompt_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_slug_id'], ['agent_slugs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('fk_users_auth_id'), 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_users_auth_id'), 'users', 'users', ['id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.drop_table('pipeline_phases')
    op.drop_table('allowed_ai_models')
    op.drop_table('agent_slugs')
    # ### end Alembic commands ###
